# Generated by Django 4.0.4 on 2022-04-27 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_no', models.CharField(max_length=5)),
                ('acc_type', models.CharField(max_length=5)),
                ('acc_id', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.TextField(blank=True, max_length=30)),
                ('cust_fname', models.TextField(blank=True, max_length=30)),
                ('cust_sname', models.TextField(blank=True, max_length=30)),
                ('acc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_id', models.CharField(blank=True, max_length=20, null=True)),
                ('dep_name', models.CharField(blank=True, max_length=45, null=True)),
                ('dep_emplpoyee', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workrs_id', models.CharField(blank=True, max_length=20, null=True)),
                ('workers_name', models.CharField(blank=True, max_length=45, null=True)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer')),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.department')),
            ],
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings_id', models.CharField(blank=True, max_length=45, null=True)),
                ('Acc_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.department')),
                ('Acc_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(blank=True, max_length=20, null=True)),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('timestam', models.DateTimeField(auto_now_add=True)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Current_Dep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(blank=True, max_length=45, null=True)),
                ('acc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.accounts')),
                ('current_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.department')),
            ],
        ),
    ]
