# Generated by Django 4.0.4 on 2022-04-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cus_username',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='acc_no',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
