# Generated by Django 4.0.4 on 2022-04-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_customer_cus_username_alter_customer_acc_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cus_username',
            new_name='cust_username',
        ),
    ]
